### ISSUE TITLE
Add kudulite remote build support for python 3.7

### ISSUE THREAD

**Issue by Hazhzeng** [Azure-App-Service/KuduLite#89]
Add checks for Python Functions App (Dedicated and Consumption).

Default the oryx build to
FRAMEWORK
FRAMEWORK_VERSION

If these two variables are not set,
we fall back to default verison

**Comment by Hazhzeng** [comment]
There's an issue on LWAS where it parses the FRAMEWORK and FRAMEWORK_VERSION, because it is separated by the pipe "|" character in LinuxFxVersion

FRAMEWORK will be mcr.microsoft.com/azure-functions/python
FRAMEWORK_VERSION 3.6

@ankitkumarr @Hazhzeng

**Comment by kulkarnisonia16** [comment]
This is for Dedicated/Premium.

**Comment by ankitkumarr** [comment]
The item is also for consumption
